version = 5.7.0
archive_dir = /etc/letsencrypt/archive/orfin-seo.plugflow.my.id
cert = /etc/letsencrypt/live/orfin-seo.plugflow.my.id/cert.pem
privkey = /etc/letsencrypt/live/orfin-seo.plugflow.my.id/privkey.pem
chain = /etc/letsencrypt/live/orfin-seo.plugflow.my.id/chain.pem
fullchain = /etc/letsencrypt/live/orfin-seo.plugflow.my.id/fullchain.pem
[renewalparams]
account = 3a6d99fd9152b255ca971bd14a830c79
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
orfin-seo.plugflow.my.id = /var/www/certbot
